baseURL = "https://tactical-advantage.trading/"
title = "Tactical Advantage"
languageCode = "en-US"
locale = "en-US"
theme = "port-hugo"

[minify]
minifyOutput = true

[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"

[[menu.main]]
name = "Tactical Advantage"
pageRef = "/"
weight = 1

[[menu.main]]
name = "eWallet"
pageRef = "/ewallet"
weight = 2

[[menu.main]]
name = "Claim eCash"
pageRef = "/claim-ecash"
weight = 3

[params]
copyright = "Tactical Advantage"
description = "Algorithmic trading, Investing & Finance"
author = "Tactical Advantage"
