baseURL = "https://tactical-advantage.trading/"
title = "Tactical Advantage"
locale = "en-US"
theme = "port-hugo"

[minify]
minifyOutput = true

[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"

[[menu.main]]
name = "About"
URL = "#about"
weight = 1

[[menu.main]]
name = "Vision"
URL = "#vision"
weight = 2

[[menu.main]]
name = "Key Wallet"
URL = "/key-wallet"
weight = 3

[[menu.main]]
name = "Claim eCash"
URL = "/claim-ecash"
weight = 4

[params]
copyright = "Tactical Advantage"
description = "Algorithmic trading, Investing & Finance"
author = "Tactical Advantage"
