baseURL = "https://tactical-advanage.trading/"
title = "Tactical Advantage"
languageCode = "en-us"
theme = "port-hugo"

[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"

[[params.plugins.css]]
link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"

[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css"

[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"

[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"

[[menu.main]]
name = "About"
URL = "#about"
weight = 1

[[menu.main]]
name = "Vision"
URL = "#vision"
weight = 2

[[menu.main]]
name = "Key Wallet"
URL = "/key-wallet"
weight = 3

[params]
copyright = "Tactical Advantage"
description = "Algorithmic trading, Investing & Finance"
author = "Tactical Advantage"
